schema:
  schema_id: luna_pinyin
  name: luna_pinyin

switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, ABC ]

engine:
  processors:
    - ascii_composer
    - speller
    - express_editor
  segmentors:
    - ascii_segmentor
    - abc_segmentor
    - fallback_segmentor
  translators:
    - script_translator
  filters:
    - uniquifier

speller:
  alphabet: zyxwvutsrqponmlkjihgfedcba
  delimiter: " "

translator:
  dictionary: luna_pinyin
  enable_user_dict: false
